# Generated by Django 4.1.1 on 2022-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nome_extenso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=200),
        ),
    ]
