# Generated by Django 4.1.1 on 2022-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_nome_extenso_alter_curso_nome_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tecnologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='url_certificado',
            field=models.URLField(blank=True, null=True),
        ),
    ]
