# Generated by Django 4.1.1 on 2022-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=100)),
                ('area_estudo', models.CharField(max_length=20)),
                ('nivel', models.CharField(blank=True, choices=[(1, 'Graduação'), (2, 'Pós_Graduação'), (3, 'Outros')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('C', 'Concluído'), ('E', 'Estudando'), ('S', 'Suspenso')], default='E', max_length=1)),
                ('categoria', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='V', max_length=1)),
                ('nome_curso', models.CharField(max_length=30)),
                ('inicio', models.DateTimeField()),
                ('conclusao', models.DateTimeField()),
            ],
        ),
    ]
