# Generated by Django 4.1.1 on 2022-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduacao',
            name='area_estudo',
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='categoria',
            field=models.CharField(choices=[('P', 'Presencial'), ('D', 'Distância')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='conclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='inicio',
            field=models.DateField(),
        ),
    ]
