# Generated by Django 4.1.1 on 2022-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduacao', '0002_remove_graduacao_area_estudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='nivel',
            field=models.CharField(blank=True, choices=[('G', 'Graduação'), ('P', 'Pós_Graduação'), ('O', 'Outros')], max_length=1, null=True),
        ),
    ]
