# Generated by Django 4.1.1 on 2022-09-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo_Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('data_inclusao', models.DateField()),
                ('data_modificacao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
